### ISSUE TITLE
Gateway improvements

### ISSUE THREAD

**Issue by r-marques** [nevermined-io/node#18]
- [x] [Improve documentation of the README ( document envs, how to run, ...)](https://github.com/nevermined-io/gateway-ts/pull/22)
- [x] #29
- [x] #30
- [ ] Clean up the npm scripts. There are some scripts that are duplicated
- [x] Adhere to the nest.js best practices
- [x] Fix all linter errors
- [x] https://github.com/nevermined-io/gateway-ts/issues/17
- [x] add proper testing to the gateway
- [x] Handle configuration properly
- [x] Remove all the `elastic search` dependencies and code related to it
- [x] Remove agreement.js and make an access service instead ... or perhaps just use nevermined service for all this
- [x] Somebody should check what is left that is shared with markeplace API, and make a common library
